### ISSUE TITLE
Running code

### ISSUE THREAD

**Issue by Ryman1262645** [Ryman1262645/HelloWorld#3]
I have no idea how to run this code

**Comment by ts-scik** [comment]
compile it using gcc?
and then run the .exe it makes?
and when you run it, pass it 3 integers?

**Comment by ts-scik** [comment]
it turns out my code was horribly broken. it now works, and compiles.
I ran it and all is fine.
The current problems are:
a) i still don't actually start or stop the timer, i just set the time variable to 0
b) you have to manually change the size variable in the Generate Random function and also pass it as an argument until I can figure out malloc for C++
